In [1]:
# import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# read the data
df = pd.read_csv("fleet_train.csv")

In [3]:
df = df[['Engine_Load',
       'Engine_Coolant_Temp','Engine_RPM','Voltage_Control_Module','Engine_Oil_Temp','Turbo_Boost_And_Vcm_Gauge']]

In [4]:
df

Engine_Load  Engine_Coolant_Temp  Engine_RPM  Voltage_Control_Module  \
0       21.568628                   88      1115.5                   14.10   
1       20.392157                   88      1782.5                   14.10   
2       43.529410                   81      1588.0                   14.20   
3       99.607840                   89      1899.5                   14.16   
4       73.333336                   89      1230.5                   14.12   
...           ...                  ...         ...                     ...   
7499    17.254902                   89      1298.0                   14.22   
7500     0.000000                   90      1158.5                   14.18   
7501    55.686275                   89      1575.5                   14.02   
7502    46.274510                   87      1412.0                   14.20   
7503    62.745100                   88      1524.5                   14.20   

      Engine_Oil_Temp  Turbo_Boost_And_Vcm_Gauge  
0                  85                   2.755716  
1                  85                   5.511435  
2                  79                   1.740453  
3                  87                   4.496170  
4                  85                   3.770981  
...               ...                        ...  
7499               87                   1.305340  
7500               88                   1.740453  
7501               86                   4.206095  
7502               83                   1.740453  
7503               83                   5.221359  

[7504 rows x 6 columns]

In [5]:
def el(x):
    if x<85:
        return 'green'
    if (x>=85) & (x<=98):
        return 'orange'
    if x>98:
        return 'red'
    
def ect(x):
    if x<90:
        return 'green'
    if (x>=90) & (x<=105):
        return 'orange'
    if x>105:
        return 'red'
    
def erpm(x):
    if x<1800:
        return 'green'
    if (x>=1800) & (x<=2200):
        return 'orange'
    if x>2200:
        return 'red'
    
def vcm(x):
    if (x>13.9) & (x<14.9):
        return 'green'
    if (x>=13) & (x<=13.9):
        return 'orange'
    if (x<13) | (x>=14.9):
        return 'red'
    
def eot(x):
    if (x<100):
        return 'green'
    if (x>=100) & (x<120):
        return 'orange'
    if (x>=120):
        return 'red'
    
def tb_vcm(x):
    if x<22:
        return 'green'
    if x>=22:
        return 'red'
     
df1 = pd.DataFrame()
df1['engine_load_category'] = df['Engine_Load'].apply(el)
df1['Engine_Coolant_Temp_category'] = df['Engine_Coolant_Temp'].apply(ect)
df1['Engine_RPM_category'] = df['Engine_RPM'].apply(erpm)
df1['Voltage_Control_Module_category'] = df['Voltage_Control_Module'].apply(vcm)
df1['Engine_Oil_Temp_category'] = df['Engine_Oil_Temp'].apply(eot)
df1['Turbo_Boost_And_Vcm_Gauge_category'] = df['Turbo_Boost_And_Vcm_Gauge'].apply(tb_vcm)
                              

In [6]:
df.columns

Index(['Engine_Load', 'Engine_Coolant_Temp', 'Engine_RPM',
       'Voltage_Control_Module', 'Engine_Oil_Temp',
       'Turbo_Boost_And_Vcm_Gauge'],
      dtype='object')

In [7]:
df1

engine_load_category Engine_Coolant_Temp_category Engine_RPM_category  \
0                   green                        green               green   
1                   green                        green               green   
2                   green                        green               green   
3                     red                        green              orange   
4                   green                        green               green   
...                   ...                          ...                 ...   
7499                green                        green               green   
7500                green                       orange               green   
7501                green                        green               green   
7502                green                        green               green   
7503                green                        green               green   

     Voltage_Control_Module_category Engine_Oil_Temp_category  \
0                              green                    green   
1                              green                    green   
2                              green                    green   
3                              green                    green   
4                              green                    green   
...                              ...                      ...   
7499                           green                    green   
7500                           green                    green   
7501                           green                    green   
7502                           green                    green   
7503                           green                    green   

     Turbo_Boost_And_Vcm_Gauge_category  
0                                 green  
1                                 green  
2                                 green  
3                                 green  
4                                 green  
...                                 ...  
7499                              green  
7500                              green  
7501                              green  
7502                              green  
7503                              green  

[7504 rows x 6 columns]

In [8]:
# condition for target variable
ls=[]
for i in range(len(df1)):
    if df1.loc[i].tolist().count('green') == 6:
        ls.append('GREEN')
        
    elif df1.loc[i].tolist().count('red') >= 1:
        ls.append('RED')
        
    elif (df1.loc[i].tolist().count('orange') < 3) & (df1.loc[i].tolist().count('red') < 1):
        ls.append('YELLOW')
        
    elif (df1.loc[i].tolist().count('orange') >= 3) & (df1.loc[i].tolist().count('red') < 1):
        ls.append('ORANGE')

In [9]:
len(ls)

7504

In [10]:
df['target'] = ls

In [11]:
df1

engine_load_category Engine_Coolant_Temp_category Engine_RPM_category  \
0                   green                        green               green   
1                   green                        green               green   
2                   green                        green               green   
3                     red                        green              orange   
4                   green                        green               green   
...                   ...                          ...                 ...   
7499                green                        green               green   
7500                green                       orange               green   
7501                green                        green               green   
7502                green                        green               green   
7503                green                        green               green   

     Voltage_Control_Module_category Engine_Oil_Temp_category  \
0                              green                    green   
1                              green                    green   
2                              green                    green   
3                              green                    green   
4                              green                    green   
...                              ...                      ...   
7499                           green                    green   
7500                           green                    green   
7501                           green                    green   
7502                           green                    green   
7503                           green                    green   

     Turbo_Boost_And_Vcm_Gauge_category  
0                                 green  
1                                 green  
2                                 green  
3                                 green  
4                                 green  
...                                 ...  
7499                              green  
7500                              green  
7501                              green  
7502                              green  
7503                              green  

[7504 rows x 6 columns]

In [12]:
df

Engine_Load  Engine_Coolant_Temp  Engine_RPM  Voltage_Control_Module  \
0       21.568628                   88      1115.5                   14.10   
1       20.392157                   88      1782.5                   14.10   
2       43.529410                   81      1588.0                   14.20   
3       99.607840                   89      1899.5                   14.16   
4       73.333336                   89      1230.5                   14.12   
...           ...                  ...         ...                     ...   
7499    17.254902                   89      1298.0                   14.22   
7500     0.000000                   90      1158.5                   14.18   
7501    55.686275                   89      1575.5                   14.02   
7502    46.274510                   87      1412.0                   14.20   
7503    62.745100                   88      1524.5                   14.20   

      Engine_Oil_Temp  Turbo_Boost_And_Vcm_Gauge  target  
0                  85                   2.755716   GREEN  
1                  85                   5.511435   GREEN  
2                  79                   1.740453   GREEN  
3                  87                   4.496170     RED  
4                  85                   3.770981   GREEN  
...               ...                        ...     ...  
7499               87                   1.305340   GREEN  
7500               88                   1.740453  YELLOW  
7501               86                   4.206095   GREEN  
7502               83                   1.740453   GREEN  
7503               83                   5.221359   GREEN  

[7504 rows x 7 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7504 entries, 0 to 7503
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Engine_Load                7504 non-null   float64
 1   Engine_Coolant_Temp        7504 non-null   int64  
 2   Engine_RPM                 7504 non-null   float64
 3   Voltage_Control_Module     7504 non-null   float64
 4   Engine_Oil_Temp            7504 non-null   int64  
 5   Turbo_Boost_And_Vcm_Gauge  7504 non-null   float64
 6   target                     7504 non-null   object 
dtypes: float64(4), int64(2), object(1)
memory usage: 410.5+ KB


In [14]:
df['target'] = list(map(lambda x: str(x).lower(),df['target']))

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()

In [17]:
df['target'] = le.fit_transform(df['target']).tolist()

In [18]:
df['target']

0       0
1       0
2       0
3       2
4       0
       ..
7499    0
7500    3
7501    0
7502    0
7503    0
Name: target, Length: 7504, dtype: int64

In [19]:
df = df.round(2)

In [20]:
df.head()

Engine_Load  Engine_Coolant_Temp  Engine_RPM  Voltage_Control_Module  \
0        21.57                   88      1115.5                   14.10   
1        20.39                   88      1782.5                   14.10   
2        43.53                   81      1588.0                   14.20   
3        99.61                   89      1899.5                   14.16   
4        73.33                   89      1230.5                   14.12   

   Engine_Oil_Temp  Turbo_Boost_And_Vcm_Gauge  target  
0               85                       2.76       0  
1               85                       5.51       0  
2               79                       1.74       0  
3               87                       4.50       2  
4               85                       3.77       0

In [21]:
df.columns

Index(['Engine_Load', 'Engine_Coolant_Temp', 'Engine_RPM',
       'Voltage_Control_Module', 'Engine_Oil_Temp',
       'Turbo_Boost_And_Vcm_Gauge', 'target'],
      dtype='object')

In [22]:
feature_cols = [x for x in df.columns if x not in 'target']

In [23]:
feature_cols

['Engine_Load',
 'Engine_Coolant_Temp',
 'Engine_RPM',
 'Voltage_Control_Module',
 'Engine_Oil_Temp',
 'Turbo_Boost_And_Vcm_Gauge']

In [24]:
from sklearn.model_selection import StratifiedShuffleSplit

In [25]:
strat_shuff_split = StratifiedShuffleSplit(n_splits = 1, test_size = 2252, random_state = 42)

In [26]:
train_idx, test_idx = next(strat_shuff_split.split(df[feature_cols], df['target']))

In [27]:
x_train = df.loc[train_idx, feature_cols]
y_train = df.loc[train_idx, 'target']

In [28]:
x_test = df.loc[test_idx, feature_cols]
y_test = df.loc[test_idx, 'target']

In [29]:
x_train.shape

(5252, 6)

In [30]:
y_test.shape

(2252,)

In [31]:
#from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [32]:
#x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3, random_state=42)

In [33]:
y_test

1736    2
3753    0
130     0
4583    0
196     0
       ..
4387    0
6539    2
2194    0
5175    0
5041    3
Name: target, Length: 2252, dtype: int64

In [35]:
y_test.unique()

array([2, 0, 3, 1], dtype=int64)

In [36]:
y_test.value_counts()

0    1651
3     512
2      86
1       3
Name: target, dtype: int64

 **Classification Algorithms** 

  **1. Random Forest Classifier**

In [37]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(x_train,y_train)
clf_prediction = clf.predict(x_test)

 **Evaluation** 

In [38]:
clf_score = accuracy_score(y_test,clf_prediction)
clf_score


0.9968916518650088

In [39]:
confusion_matrix(y_test, clf_prediction)

array([[1651,    0,    0,    0],
       [   0,    1,    0,    2],
       [   1,    0,   84,    1],
       [   3,    0,    0,  509]], dtype=int64)

In [40]:
print(classification_report(y_test,clf_prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1651
           1       1.00      0.33      0.50         3
           2       1.00      0.98      0.99        86
           3       0.99      0.99      0.99       512

    accuracy                           1.00      2252
   macro avg       1.00      0.83      0.87      2252
weighted avg       1.00      1.00      1.00      2252



 **2. AdaBoost**

In [41]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
ada.fit(x_train,y_train)
ada_prediction = ada.predict(x_test)

 **Evaluation** 

In [42]:
ada_score = accuracy_score(ada_prediction,y_test)
ada_score


0.9551509769094139

In [43]:
confusion_matrix(y_test, ada_prediction)

array([[1651,    0,    0,    0],
       [   0,    0,    0,    3],
       [   1,    0,   85,    0],
       [  97,    0,    0,  415]], dtype=int64)

In [44]:
print(classification_report(y_test,ada_prediction))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97      1651
           1       0.00      0.00      0.00         3
           2       1.00      0.99      0.99        86
           3       0.99      0.81      0.89       512

    accuracy                           0.96      2252
   macro avg       0.73      0.70      0.71      2252
weighted avg       0.96      0.96      0.95      2252



C:\Users\guest23455\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


 **3. Support Vector Classifier**

In [45]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train,y_train)
svc_prediction = svc.predict(x_test)

**Evaluation**

In [46]:
svc_score = accuracy_score(y_test,svc_prediction)
svc_score

0.7793072824156305

In [47]:
confusion_matrix(y_test, svc_prediction)

array([[1643,    0,    0,    8],
       [   0,    0,    0,    3],
       [  60,    0,    6,   20],
       [ 406,    0,    0,  106]], dtype=int64)

In [48]:
print(classification_report(y_test,svc_prediction))

              precision    recall  f1-score   support

           0       0.78      1.00      0.87      1651
           1       0.00      0.00      0.00         3
           2       1.00      0.07      0.13        86
           3       0.77      0.21      0.33       512

    accuracy                           0.78      2252
   macro avg       0.64      0.32      0.33      2252
weighted avg       0.79      0.78      0.72      2252



C:\Users\guest23455\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


 **4. K Nearest Neighbor**

In [49]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
knn_prediction = knn.predict(x_test)

**Evaluation**

In [50]:
knn_score = accuracy_score(y_test,knn_prediction)
knn_score


0.8423623445825933

In [51]:
confusion_matrix(y_test, knn_prediction)

array([[1608,    0,    0,   43],
       [   0,    0,    0,    3],
       [   1,    0,   72,   13],
       [ 276,    0,   19,  217]], dtype=int64)

In [52]:
print(classification_report(y_test,knn_prediction))

              precision    recall  f1-score   support

           0       0.85      0.97      0.91      1651
           1       0.00      0.00      0.00         3
           2       0.79      0.84      0.81        86
           3       0.79      0.42      0.55       512

    accuracy                           0.84      2252
   macro avg       0.61      0.56      0.57      2252
weighted avg       0.83      0.84      0.82      2252



C:\Users\guest23455\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**5. XGBoost**

In [53]:
import xgboost as xgb
xgb_clf = xgb.XGBClassifier(max_depth=5, learning_rate=0.1, n_estimators=100)
xgb_clf.fit(x_train,y_train)
xgb_prediction = xgb_clf.predict(x_test)

**Evaluation** 

In [54]:
xgb_score = accuracy_score(y_test,xgb_prediction)
xgb_score

0.9982238010657194

In [55]:
confusion_matrix(y_test, xgb_prediction)

array([[1651,    0,    0,    0],
       [   0,    2,    0,    1],
       [   0,    0,   85,    1],
       [   2,    0,    0,  510]], dtype=int64)

In [56]:
print(classification_report(y_test,xgb_prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1651
           1       1.00      0.67      0.80         3
           2       1.00      0.99      0.99        86
           3       1.00      1.00      1.00       512

    accuracy                           1.00      2252
   macro avg       1.00      0.91      0.95      2252
weighted avg       1.00      1.00      1.00      2252



**6. Gaussian Naive Bayes**

In [57]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
gnb_prediction = gnb.predict(x_test)


**Evaluation** 

In [58]:
gnb_score = accuracy_score(y_test,gnb_prediction)
gnb_score

0.8219360568383659

In [59]:
confusion_matrix(y_test, gnb_prediction)

array([[1541,    0,    9,  101],
       [   0,    1,    1,    1],
       [   2,    1,   19,   64],
       [ 188,   11,   23,  290]], dtype=int64)

In [60]:
print(classification_report(y_test,gnb_prediction))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91      1651
           1       0.08      0.33      0.12         3
           2       0.37      0.22      0.28        86
           3       0.64      0.57      0.60       512

    accuracy                           0.82      2252
   macro avg       0.49      0.51      0.48      2252
weighted avg       0.81      0.82      0.82      2252



**7. Logistic Regression**

In [61]:
from sklearn.linear_model import LogisticRegression
lreg = LogisticRegression()
lreg.fit(x_train,y_train)
logistic_prediction = lreg.predict(x_test)


C:\Users\guest23455\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [62]:
logistic_score = accuracy_score(y_test,logistic_prediction)
logistic_score

0.7717584369449378

In [63]:
confusion_matrix(y_test, logistic_prediction)

array([[1578,    0,    1,   72],
       [   0,    0,    1,    2],
       [  18,    0,   26,   42],
       [ 357,    0,   21,  134]], dtype=int64)

In [64]:
print(classification_report(y_test,logistic_prediction))

              precision    recall  f1-score   support

           0       0.81      0.96      0.88      1651
           1       0.00      0.00      0.00         3
           2       0.53      0.30      0.39        86
           3       0.54      0.26      0.35       512

    accuracy                           0.77      2252
   macro avg       0.47      0.38      0.40      2252
weighted avg       0.73      0.77      0.74      2252



C:\Users\guest23455\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [65]:
results_df = pd.DataFrame({"Algorithm":["Random Forest Classifier","AdaBoost Classifier","Support Vector Classifier","K Nearest Neighbor","XGBoost Classifier","Gaussian Naive Bayes","Logistic Regression"],
                           "Accuracy score":[clf_score,ada_score,svc_score,knn_score,xgb_score,gnb_score,logistic_score]})
results_df

Algorithm  Accuracy score
0   Random Forest Classifier        0.996892
1        AdaBoost Classifier        0.955151
2  Support Vector Classifier        0.779307
3         K Nearest Neighbor        0.842362
4         XGBoost Classifier        0.998224
5       Gaussian Naive Bayes        0.821936
6        Logistic Regression        0.771758

In [ ]:
test = pd.read_csv("fleet_test.csv")

In [ ]:
test

In [ ]:
test.columns

In [ ]:
test = test[['Measurement_timestamp','Engine_Load', 'Engine_Coolant_Temp',
       'Engine_RPM', 'Voltage_Control_Module', 'Engine_Oil_Temp',
       'Turbo_Boost_And_Vcm_Gauge','truckid']]

In [ ]:
test

In [ ]:
test_predictions = clf.predict(test[['Engine_Load', 'Engine_Coolant_Temp',
       'Engine_RPM', 'Voltage_Control_Module', 'Engine_Oil_Temp',
       'Turbo_Boost_And_Vcm_Gauge']])

In [ ]:
test['prediction'] = le.inverse_transform(test_predictions)

In [ ]:
test

In [ ]:
test['prediction'].unique()

In [ ]:
test['prediction'] = test['prediction'].map({'red':4,'orange':3, 'yellow':2, 'green':1})

In [ ]:
test['prediction'].value_counts()

In [ ]:
test.groupby('truckid')['prediction'].max().value_counts()


In [ ]:
test.groupby('truckid')['prediction'].max()